title: "One Hundred Hellos"
#url: "http://daneroo.github.com"
url: "http://onehundredhellos.daniel-lauzon.com"
author: "Daniel Lauzon"
email: "daniel.lauzon@gmail.com"
description: "The personal blog of Daniel Lauzon."

auto: false
source: .
paginate: 15
paginate_file: index.html

permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.md
  - _drafts
  - Rakefile
  - import
