title: "Daniel (S) Lauzon"
#url: "http://daneroo.github.com"
url: "http://m.daniel-lauzon.com"
author: "Daniel Lauzon"
email: "daniel.lauzon@gmail.com"
description: "Portfolio and Blog"

auto: false
source: .
paginate: 10
paginate_file: index.html

permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.md
  - _drafts
  - Rakefile
  - import
  - initializr