title: "Daniel Lauzon"
url: "http://daniel-lauzon.com"
author: "Daniel Lauzon"
email: "daniel.lauzon@gmail.com"
description: "Portfolio and Blog"

auto: false
source: .
#paginate: 10
#paginate_file: blog.html

permalink: /:year/:month/:title

# Replaced rdiscount because of deprecation
markdown: GFM

exclude:
  - README.md
  - Rakefile
