title: "Daniel Lauzon"
url: "http://daniel-lauzon.com"
author: "Daniel Lauzon"
email: "daniel.lauzon@gmail.com"
description: "Portfolio and Blog"

auto: false
source: .
#paginate: 10
#paginate_file: blog.html

permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.md
  - Rakefile
